name: Build and Release
on:
  push:
    branches:
      - prod
jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Creating react static build
        run: |
          yarn
          yarn workspace coc-client build
        env:
          CI: false
      - name: Compressing server source code and frontend build folders
        run: |
          tar -zcf server.tar.gz ./server
          tar -zcf client.tar.gz ./new_client/build
        env:
          CI: false
      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::Release-$(date +"%Y.%m.%d-%H%M")"
      - name: Uploading assets to release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: |
            server.tar.gz
            client.tar.gz
